
# 工作目录
[general]
working_directory = "~/"
# 导入颜色方案
import = ["./gruvbox_dark.toml"]

# Shell
[terminal]
shell = { program = "/bin/zsh" }

# 字体设置
[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 18.0

# 窗口配置
[window]
opacity = 0.9
padding = { x = 10, y = 5 }
decorations = "full"

# 环境变量
[env]
TERM = "xterm-256color"

# 快捷键
[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" }
]

[cursor]
style = {shape="Block", blinking="Never"}
unfocused_hollow = false

[colors]
cursor = { text = "#000000", cursor = "#00FF00"}
